package com.whydigit.wms.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.whydigit.wms.entity.StockDetailsVO;

@Repository
public interface StockDetailsRepo extends JpaRepository<StockDetailsVO, Long> {

	@Query(nativeQuery = true, value = "select sum(sqty) from stockdetails  WHERE orgid = ?1 and pckey='CHILD' AND client = ?3 AND branchcode = ?2 AND warehouse = ?5 AND partno =?4 and grnno=?6 and bin='BULK' AND status = 'V';")
	Set<Object[]> getQtyDetais(Long orgId, String branchCode, String client, String partNo, String warehouse,
			String grnno);

	@Query(nativeQuery = true, value = "select sum(a.sqty)sqty from(\r\n"
			+ "(select partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bintype,binclass,celltype,core,bin,qcflag,sum(sqty)sqty from stockdetails \r\n"
			+ "where orgid=?1 and branchcode=?2 and warehouse=?3 and client=?4 and status='R' and bin=?5 and partno=?6 and grnno=?7\r\n"
			+ "and batch=?8 or batch is null \r\n"
			+ "group by partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bintype,binclass,celltype,core,bin,qcflag having sum(sqty)>0)) a")
	int getAvlQty(Long orgId, String branchCode, String warehouse, String client, String fromBin, String partNo,
			String grnNo, String batchNo);

	@Query(nativeQuery = true, value = "select sum(a.sqty)sqty from\r\n"
			+ "(select partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bintype,binclass,celltype,core,bin,qcflag,sum(sqty)sqty from stockdetails \r\n"
			+ "where orgid=?1 and branchcode=?2 and warehouse=?3 and client=?4 and status=?9 and bin=?5 and partno=?6 and grnno=?7\r\n"
			+ "and batch=?8 or batch is null\r\n"
			+ "group by partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bintype,binclass,celltype,core,bin,qcflag having sum(sqty)>0) a")
	int getAvlQtyforVasPick(Long orgId, String branchCode, String warehouse, String client, String fromBin,
			String partNo, String grnNo, String batchNo, String status);

	@Query(value = "select batch,expdate,batchdate from stockdetails where orgid=?1 and branchcode=?2 and client=?3 and status='R'and warehouse=?4 and partno=?5\r\n"
			+ "		group by batch,expdate,batchdate", nativeQuery = true)
	Set<Object[]> getDetails(Long orgId, String branchCode, String client, String warehouse, String partNo);

	@Query(nativeQuery = true, value = "select sum(a.sqty)sqty from(\r\n"
			+ "(select partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bintype,binclass,celltype,core,bin,qcflag,sum(sqty)sqty from stockdetails \r\n"
			+ "where orgid=?1 and branchcode=?2 and warehouse=?3 and client=?4 and status='V' and bin=?5 and partno=?6 and grnno=?7\r\n"
			+ "and batch=?8 or batch is null\r\n"
			+ "group by partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bintype,binclass,celltype,core,bin,qcflag having sum(sqty)>0)) a")
	int getAvlQtyforVasPutaway(Long orgId, String branchCode, String warehouse, String client, String fromBin,
			String partNo, String grnNo, String batchNo);

	@Query(nativeQuery = true, value = "select cast(a.sqty as unsigned)sqty from(\r\n"
			+ "            select partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bintype,binclass,celltype,core,bin,qcflag,sum(sqty)sqty from stockdetails \r\n"
			+ "			where orgid=?1 and branch=?2 and branchcode=?3 and client=?4 and bin=?5 AND PARTNO=?6 and grnno=?7 and ( batch=?8 or batch is null )\r\n"
			+ "			group by partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bintype,binclass,celltype,core,bin,qcflag having sum(sqty)>0\r\n"
			+ "            ) a")
	Integer findAvlQtyForLocationMovement(Long orgId, String branch, String branchCode, String client, String bin,
			String partNo, String grnNo, String batchNo);

	@Query(nativeQuery = true, value = "SELECT CAST(a.sqty AS UNSIGNED) AS sqty " + "FROM (" + "    SELECT "
			+ "        SUM(sqty) AS sqty " + "    FROM stockdetails " + "    WHERE " + "        orgid = ?1 "
			+ "        AND branchcode = ?2 " + "        AND client = ?3 " + "        AND warehouse = ?4 "
			+ "        AND bin = ?8 " + "        AND partno = ?5 " + "        AND grnno = ?6 "
			+ "        AND (batch = ?7 or batch is null) " + "        AND status = 'R' "
			+ "        AND pckey = 'CHILD' " + "    GROUP BY "
			+ "        partno, partdesc, sku, grnno, grndate, batch, batchdate, expdate, "
			+ "        bintype, binclass, celltype, core, bin, qcflag " + "    HAVING SUM(sqty) > 0 " + ") a")
	int getKittingQtyDetails(Long orgId, String branchCode, String client, String warehouse, String partNo,
			String grnNo, String batch, String bin);

	@Query(nativeQuery = true, value = "select partno,partdesc,sku from stockdetails where orgid=?1 and branchcode=?2 and client=?3 and status='R'and warehouse=?4\r\n"
			+ "		group by partno,partdesc,sku")
	Set<Object[]> getPartNo(Long orgId, String branchCode, String client, String warehouse);

	@Query(nativeQuery = true, value = "select cast(sum(sqty) as unsigned)sqty from stockdetails where orgid=?1 and branchcode=?2 and client=?3 and status='R'and warehouse=?4 and partno=?5 and batch=?6 or batch is null")
	int getAvlQtyforBuyerOrder(Long orgId, String branchCode, String client, String warehouse, String partNo,
			String batchNo);

	@Query(nativeQuery = true, value = "SELECT b.partno, \r\n"
			+ "       b.partdesc, \r\n"
			+ "       COALESCE(SUM(a.sqty), 0) AS avlqty \r\n"
			+ "FROM material b \r\n"
			+ "LEFT OUTER JOIN stockdetails a \r\n"
			+ "ON a.partno = b.partno \r\n"
			+ "   AND a.orgid = b.orgid \r\n"
			+ "   AND a.customer = b.customer \r\n"
			+ "   AND (b.cbranch = a.branchcode OR b.cbranch = 'ALL') \r\n"
			+ "   AND a.client = b.client\r\n"
			+ "   AND a.orgid = ?1\r\n"
			+ "   AND a.branchcode = ?2\r\n"
			+ "   AND a.warehouse = ?3\r\n"
			+ "   AND a.customer = ?4\r\n"
			+ "   AND a.client = ?5\r\n"
			+ "   AND a.stockdate <= DATE(NOW()) \r\n"
			+ "WHERE (b.partno = ?6 OR ?6 = 'ALL') \r\n"
			+ "GROUP BY b.partno, b.partdesc having COALESCE(SUM(a.sqty)) >0 ")
	Set<Object[]> getConsolidateStockDetails(Long orgId, String branchCode, String warehouse, String customer,
			String client, String partNo);

	@Query(nativeQuery = true, value = "SELECT bin, \r\n"
			+ "       batch, \r\n"
			+ "       partno, \r\n"
			+ "       partdesc, \r\n"
			+ "       CASE \r\n"
			+ "           WHEN status = 'R' THEN 'Release'\r\n"
			+ "           WHEN status = 'V' THEN 'Vas'\r\n"
			+ "           WHEN status = 'H' THEN 'Hold'\r\n"
			+ "           ELSE 'Defective'\r\n"
			+ "       END AS status, \r\n"
			+ "       COALESCE(SUM(sqty), 0) AS avlqty\r\n"
			+ "FROM stockdetails\r\n"
			+ "WHERE orgid = ?1\r\n"
			+ "  AND branchcode = ?2\r\n"
			+ "  AND warehouse = ?3\r\n"
			+ "  AND customer = ?4\r\n"
			+ "  AND client = ?5\r\n"
			+ "  AND stockdate <= CURDATE()\r\n"
			+ "  AND (partno = ?6 OR 'ALL' = ?6)\r\n"
			+ "  AND (batch = ?7 OR 'ALL' = ?7)\r\n"
			+ "  AND (bin = ?8 OR 'ALL' = ?8)\r\n"
			+ "  AND (status = CASE WHEN 'Release' = ?9 THEN 'R'\r\n"
			+ "                      WHEN 'Vas' = ?9 THEN 'V'\r\n"
			+ "                      WHEN 'Hold' = ?9 THEN 'H'\r\n"
			+ "                      else  'D'\r\n"
			+ "                 END OR 'ALL' = ?9)\r\n"
			+ "GROUP BY bin, batch, partno, partdesc, status having sum(sqty)>0")
	Set<Object[]> findStockReportBinAndBatchWise(Long orgId, String branchCode, String warehouse, String customer,
			String client, String partNo, String batch, String bin, String status);

	@Query(nativeQuery = true, value = "select a.partno from(\r\n"
			+ "SELECT b.bin, b.batch, b.partno, b.partdesc, b.status, COALESCE(SUM(b.sqty), 0) AS avlqty\r\n"
			+ "FROM stockdetails b\r\n" + "WHERE b.orgid = ?1 \r\n" + "  AND b.branchcode = ?2 \r\n"
			+ "  AND b.warehouse = ?3\r\n" + "  AND b.customer = ?4\r\n" + "  AND b.client = ?5\r\n"
			+ "  AND b.stockdate <= CURDATE()\r\n"
			+ "GROUP BY b.bin, b.batch, b.partno, b.partdesc, status having sum(b.sqty)>0)a group by a.partno")
	Set<Object[]> findPartNoForStockReportBinAndBatchWise(Long orgId, String branchCode, String warehouse,
			String customer, String client);

	@Query(nativeQuery = true, value = "SELECT a.batch \r\n"
			+ "FROM (\r\n"
			+ "    SELECT 'ALL' AS bin, 'ALL' AS batch, 'ALL' AS partno, 'ALL' AS partdesc, 'ALL' AS status, 0 AS avlqty\r\n"
			+ "    UNION ALL\r\n"
			+ "    SELECT b.bin, \r\n"
			+ "           b.batch, \r\n"
			+ "           b.partno, \r\n"
			+ "           b.partdesc, \r\n"
			+ "           b.status, \r\n"
			+ "           COALESCE(SUM(b.sqty), 0) AS avlqty\r\n"
			+ "    FROM stockdetails b\r\n"
			+ "    WHERE b.orgid = ?1 \r\n"
			+ "      AND b.branchcode = ?2 \r\n"
			+ "      AND b.warehouse = ?3\r\n"
			+ "      AND b.customer = ?4 \r\n"
			+ "      AND b.client = ?5 \r\n"
			+ "      AND (b.partno = ?6 OR 'ALL' = ?6) \r\n"
			+ "      AND b.stockdate <= CURDATE()\r\n"
			+ "    GROUP BY b.bin, b.batch, b.partno, b.partdesc, b.status \r\n"
			+ "    HAVING SUM(b.sqty) > 0\r\n"
			+ ") a \r\n"
			+ "GROUP BY a.batch")
	Set<Object[]> findBatchForStockReportBinAndBatchWise(Long orgId, String branchCode, String warehouse,
			String customer, String client, String partNo);

	@Query(nativeQuery = true, value = "SELECT a.bin \r\n"
			+ "FROM (\r\n"
			+ "    SELECT 'ALL' AS bin, 'ALL' AS batch, 'ALL' AS partno, 'ALL' AS partdesc,'ALL' status, 0 AS avlqty\r\n"
			+ "    UNION ALL\r\n"
			+ "    SELECT b.bin, \r\n"
			+ "           b.batch, \r\n"
			+ "           b.partno, \r\n"
			+ "           b.partdesc, \r\n"
			+ "           b.status, \r\n"
			+ "           COALESCE(SUM(b.sqty), 0) AS avlqty\r\n"
			+ "    FROM stockdetails b\r\n"
			+ "    WHERE b.orgid = ?1\r\n"
			+ "      AND b.branchcode = ?2\r\n"
			+ "      AND b.warehouse = ?3\r\n"
			+ "      AND b.customer = ?4\r\n"
			+ "      AND b.client = ?5\r\n"
			+ "      AND (b.partno = ?6 OR 'ALL' = ?6)\r\n"
			+ "      AND (b.batch = ?7 OR 'ALL' = ?7)\r\n"
			+ "      AND b.stockdate <= CURDATE()\r\n"
			+ "    GROUP BY b.bin, b.batch, b.partno, b.partdesc, b.status \r\n"
			+ "    HAVING SUM(b.sqty) > 0\r\n"
			+ ") a \r\n"
			+ "GROUP BY a.bin")
	Set<Object[]> findBinForStockReportBinAndBatchWise(Long orgId, String branchCode, String warehouse, String customer,
			String client, String partNo, String batch);

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    CASE \r\n"
			+ "        WHEN a.status = 'ALL' THEN 'ALL'  -- Handle 'ALL' status explicitly\r\n"
			+ "        WHEN a.status = 'R' THEN 'Release'\r\n"
			+ "        WHEN a.status = 'V' THEN 'Vas'\r\n"
			+ "        WHEN a.status = 'H' THEN 'Hold'\r\n"
			+ "        ELSE 'Defective'\r\n"
			+ "    END AS status\r\n"
			+ "FROM (\r\n"
			+ "    SELECT b.bin, \r\n"
			+ "           b.batch, \r\n"
			+ "           b.partno, \r\n"
			+ "           b.partdesc, \r\n"
			+ "           b.status, \r\n"
			+ "           COALESCE(SUM(b.sqty), 0) AS avlqty\r\n"
			+ "    FROM stockdetails b\r\n"
			+ "    WHERE b.orgid = ?1  -- Parameter 1 for orgid\r\n"
			+ "      AND b.branchcode = ?2  -- Parameter 2 for branchcode\r\n"
			+ "      AND b.warehouse = ?3  -- Parameter 3 for warehouse\r\n"
			+ "      AND b.customer = ?4  -- Parameter 4 for customer\r\n"
			+ "      AND b.client = ?5  -- Parameter 5 for client\r\n"
			+ "      AND (b.partno = ?6 OR ?6 = 'ALL')  -- Parameter 6 for partno\r\n"
			+ "      AND (b.batch = ?7 OR ?7 = 'ALL')  -- Parameter 7 for batch\r\n"
			+ "      AND (b.bin = ?8 OR ?8 = 'ALL')  -- Parameter 8 for bin\r\n"
			+ "      AND b.stockdate <= CURDATE()\r\n"
			+ "    GROUP BY b.bin, b.batch, b.partno, b.partdesc, b.status\r\n"
			+ "    HAVING SUM(b.sqty) > 0\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT 'ALL' AS bin, 'ALL' AS batch, 'ALL' AS partno, 'ALL' AS partdesc, \r\n"
			+ "           'ALL' AS status, 0 AS avlqty\r\n"
			+ ") a\r\n"
			+ "GROUP BY a.status")
	Set<Object[]> findStatusForStockReportBinAndBatchWise(Long orgId, String branchCode, String warehouse,
			String customer, String client, String partNo, String batch, String bin);

@Query(value ="SELECT b.partno, b.partdesc, b.bin, COALESCE(SUM(b.sqty), 0) AS avlqty \r\n"
		+ "FROM stockdetails b \r\n"
		+ "WHERE b.orgid = ?1\r\n"
		+ "AND b.branchcode = ?2\r\n"
		+ "AND (b.bin = ?3 OR 'ALL' = ?3)\r\n"
		+ "AND b.warehouse = ?4\r\n"
		+ "AND b.customer = ?5\r\n"
		+ "AND b.client = ?6\r\n"
		+ "AND b.stockdate <= DATE(NOW()) \r\n"
		+ "AND (b.partno = ?7 OR 'ALL' = ?7)\r\n"
		+ "GROUP BY b.partno, b.partdesc, b.bin \r\n"
		+ "HAVING SUM(b.sqty) > 0 \r\n"
		+ "ORDER BY b.partno, b.bin;\r\n"
		+ "",nativeQuery =true)
Set<Object[]> getStockReportBinWise(Long orgId, String branchCode, String bin, String warehouse, String customer,
		String client, String partNo);

@Query(value="SELECT b.partno, \r\n"
		+ "       b.partdesc, \r\n"
		+ "       b.batch, \r\n"
		+ "       COALESCE(SUM(b.sqty), 0) AS avlqty \r\n"
		+ "FROM stockdetails b \r\n"
		+ "WHERE b.orgid =?1 \r\n"
		+ "  AND b.branchcode =?2 \r\n"
		+ "  AND (b.batch = ?3 OR 'ALL' = ?3) \r\n"
		+ "  AND b.warehouse =?4\r\n"
		+ "  AND b.customer = ?5\r\n"
		+ "  AND b.client =?6\r\n"
		+ "  AND b.stockdate <= DATE(NOW()) \r\n"
		+ "  AND (b.partno =?7 OR 'ALL' = ?7)\r\n"
		+ "GROUP BY b.partno, b.partdesc, b.batch \r\n"
		+ "HAVING avlqty > 0 \r\n"
		+ "ORDER BY b.partno, b.batch, b.partdesc",nativeQuery = true)
Set<Object[]> getStockReportBatchWise(Long orgId, String branchCode, String batch, String warehouse, String customer,
		String client, String partNo);

@Query(value="SELECT a.partno\r\n"
		+ "FROM (\r\n"
		+ "    SELECT b.partno, \r\n"
		+ "           b.partdesc, \r\n"
		+ "           b.batch, \r\n"
		+ "           COALESCE(SUM(b.sqty), 0) AS avlqty \r\n"
		+ "    FROM stockdetails b \r\n"
		+ "    WHERE b.orgid =?1\r\n"
		+ "      AND b.branchcode =?2\r\n"
		+ "      AND b.warehouse =?3\r\n"
		+ "      AND b.customer =?4\r\n"
		+ "      AND b.client =?5\r\n"
		+ "      AND b.stockdate <= DATE(NOW())\r\n"
		+ "    GROUP BY b.partno, b.partdesc, b.batch\r\n"
		+ "    HAVING avlqty > 0 order by  b.partno, b.batch, b.partdesc\r\n"
		+ ") a\r\n"
		+ "GROUP BY a.partno",nativeQuery = true)
Set<Object[]> getPartNoFromBatchWiseReport(Long orgId, String branchCode,String warehouse, String customer,
		String client);

@Query(nativeQuery = true,value="SELECT a.partno, a.partdesc, a.refno, a.sourcescreenname, \r\n"
		+ "       SUM(openingqty) AS oqty, \r\n"
		+ "       SUM(recqty) AS recqty, \r\n"
		+ "       SUM(ABS(dispatchqty)) AS dqty, \r\n"
		+ "       SUM(closingqty) AS cqty \r\n"
		+ "FROM (\r\n"
		+ "    SELECT partno, partdesc, refno, sourcescreenname, \r\n"
		+ "           SUM(sqty) AS openingqty, 0 AS recqty, 0 AS dispatchqty, 0 AS closingqty, createdon\r\n"
		+ "    FROM stockdetails \r\n"
		+ "    WHERE orgid = ?1\r\n"
		+ "      AND branchcode = ?2\r\n"
		+ "      AND warehouse = ?3\r\n"
		+ "      AND customer = ?4\r\n"
		+ "      AND client = ?5\r\n"
		+ "      AND stockdate < ?6\r\n"
		+ "      AND (partno = ?8 OR 'ALL' = ?8) \r\n"
		+ "    GROUP BY partno, partdesc, refno, sourcescreenname, createdon\r\n"
		+ "    HAVING SUM(sqty) > 0\r\n"
		+ "\r\n"
		+ "    UNION\r\n"
		+ "\r\n"
		+ "    SELECT partno, partdesc, refno, sourcescreenname, \r\n"
		+ "           0 AS openingqty, SUM(sqty) AS recqty, 0 AS dispatchqty, 0 AS closingqty, createdon \r\n"
		+ "    FROM stockdetails \r\n"
		+ "    WHERE orgid = ?1\r\n"
		+ "      AND branchcode = ?2\r\n"
		+ "      AND warehouse = ?3\r\n"
		+ "      AND customer = ?4\r\n"
		+ "      AND client = ?5\r\n"
		+ "      AND stockdate BETWEEN ?6 AND ?7\r\n"
		+ "      AND sqty > 0 \r\n"
		+ "      AND sourcescreenname NOT IN ('VAS PICK')\r\n"
		+ "      AND (partno = ?8 OR 'ALL' = ?8)\r\n"
		+ "    GROUP BY partno, partdesc, refno, sourcescreenname, createdon\r\n"
		+ "\r\n"
		+ "    UNION\r\n"
		+ "\r\n"
		+ "    SELECT partno, partdesc, refno, sourcescreenname, \r\n"
		+ "           0 AS openingqty, 0 AS recqty, SUM(sqty) AS dispatchqty, 0 AS closingqty, createdon\r\n"
		+ "    FROM stockdetails \r\n"
		+ "    WHERE orgid = ?1\r\n"
		+ "      AND branchcode = ?2\r\n"
		+ "      AND warehouse = ?3\r\n"
		+ "      AND customer = ?4\r\n"
		+ "      AND client = ?5\r\n"
		+ "      AND stockdate BETWEEN ?6 AND ?7\r\n"
		+ "      AND sqty < 0 \r\n"
		+ "      AND sourcescreenname NOT IN ('VAS PUTAWAY')\r\n"
		+ "      AND (partno = ?8 OR 'ALL' = ?8)\r\n"
		+ "    GROUP BY partno, partdesc, refno, sourcescreenname, createdon\r\n"
		+ "\r\n"
		+ "    UNION\r\n"
		+ "\r\n"
		+ "    SELECT partno, partdesc, refno, sourcescreenname, \r\n"
		+ "           0 AS openingqty, 0 AS recqty, 0 AS dispatchqty, SUM(sqty) AS closingqty, createdon \r\n"
		+ "    FROM stockdetails \r\n"
		+ "    WHERE orgid = ?1\r\n"
		+ "      AND branchcode = ?2\r\n"
		+ "      AND warehouse = ?3\r\n"
		+ "      AND customer = ?4\r\n"
		+ "      AND client = ?5\r\n"
		+ "      AND stockdate <= ?7\r\n"
		+ "      AND (partno = ?8 OR 'ALL' = ?8)\r\n"
		+ "    GROUP BY partno, partdesc, refno, sourcescreenname, createdon\r\n"
		+ "    HAVING SUM(sqty) > 0\r\n"
		+ "\r\n"
		+ ") a \r\n"
		+ "GROUP BY a.partno, a.partdesc, a.refno, a.sourcescreenname, a.createdon \r\n"
		+ "ORDER BY a.createdon ASC")
Set<Object[]>getLedgerDetails(Long orgId, String branchCode, String warehouse, String customer,
		String client, String startDate,String endDate,String partNo);

@Query(value ="select a.partno from(\r\n"
		+ "SELECT b.partno, b.partdesc, b.bin, COALESCE(SUM(b.sqty), 0) AS avlqty\r\n"
		+ "FROM stockdetails b\r\n"
		+ "WHERE b.orgid = ?1 \r\n"
		+ "  AND b.branchcode = ?2 \r\n"
		+ "  AND b.warehouse = ?3\r\n"
		+ "  AND b.customer = ?4\r\n"
		+ "  AND b.client = ?5\r\n"
		+ "AND b.stockdate <= DATE(NOW())\r\n"
		+ "GROUP BY b.partno, b.partdesc, b.bin\r\n"
		+ "HAVING SUM(b.sqty) > 0\r\n"
		+ "ORDER BY b.partno, b.bin)a group by a.partno" ,nativeQuery =true)
Set<Object[]> getStockPartNoBatch(Long orgId, String branchCode, String warehouse, String customer, String client);

@Query(value ="SELECT a.bin \r\n"
		+ "FROM (\r\n"
		+ "    SELECT 'ALL' AS partno, 'ALL' AS partdesc, 'ALL' AS bin, 0 AS avlqty\r\n"
		+ "    UNION ALL\r\n"
		+ "    SELECT b.partno, \r\n"
		+ "           b.partdesc, \r\n"
		+ "           b.bin, \r\n"
		+ "           COALESCE(SUM(b.sqty), 0) AS avlqty\r\n"
		+ "    FROM stockdetails b\r\n"
		+ "    WHERE b.orgid = ?1 \r\n"
		+ "      AND b.branchcode = ?2 \r\n"
		+ "      AND b.warehouse = ?3\r\n"
		+ "      AND b.customer = ?4\r\n"
		+ "      AND b.client = ?5\r\n"
		+ "      AND b.stockdate <= DATE(NOW())\r\n"
		+ "      AND (b.partno = ?6 OR 'ALL' = ?6)\r\n"
		+ "    GROUP BY b.partno, b.partdesc, b.bin\r\n"
		+ "    HAVING SUM(b.sqty) > 0\r\n"
		+ ") a \r\n"
		+ "GROUP BY a.bin",nativeQuery =true)
Set<Object[]> getBatchNoBin(Long orgId, String branchCode, String warehouse, String customer, String client,
		String partNo);

@Query(nativeQuery = true,value="SELECT a.batch\r\n"
		+ "FROM (\r\n"
		+ "    SELECT 'ALL' AS partno, 'ALL' AS partdesc, 'ALL' AS batch, 0 AS avlqty\r\n"
		+ "    UNION\r\n"
		+ "    SELECT b.partno, \r\n"
		+ "           b.partdesc, \r\n"
		+ "           b.batch, \r\n"
		+ "           COALESCE(SUM(b.sqty), 0) AS avlqty\r\n"
		+ "    FROM stockdetails b\r\n"
		+ "    WHERE b.orgid = ?1\r\n"
		+ "      AND b.branchcode = ?2\r\n"
		+ "      AND b.warehouse = ?3\r\n"
		+ "      AND b.customer = ?4\r\n"
		+ "      AND b.client = ?5\r\n"
		+ "      AND (b.partno = ?6 OR 'ALL' = ?6)\r\n"
		+ "      AND b.stockdate <= DATE(NOW())\r\n"
		+ "    GROUP BY b.partno, b.partdesc, b.batch\r\n"
		+ "    HAVING avlqty > 0\r\n"
		+ ") a\r\n"
		+ "GROUP BY a.batch")
Set<Object[]> getBatchFromBatchWiseReport(Long orgId, String branchCode,String warehouse, String customer,
		String client,String partNo);

boolean existsByPartnoAndOrgIdAndClient(String partNo, Long orgId, String client);

boolean existsByPartnoAndBatchAndOrgIdAndClient(String partNo, String batchNo, Long orgId, String client);


@Query(value = "SELECT\r\n"
		+ "    s.partno,\r\n"
		+ "    s.partdesc,\r\n"
		+ "    s.sku,\r\n"
		+ "    s.total_sqtyt AS qty,\r\n"
		+ "    'Low Qty' AS status\r\n"
		+ "FROM\r\n"
		+ "    (SELECT \r\n"
		+ "        partno,\r\n"
		+ "        partdesc,\r\n"
		+ "        sku,\r\n"
		+ "        SUM(sqty) AS total_sqtyt\r\n"
		+ "     FROM stockdetails\r\n"
		+ "     WHERE\r\n"
		+ "        status = 'R'\r\n"
		+ "        AND orgid =?1\r\n"
		+ "    AND client =?3\r\n"
		+ "    AND branchcode =?2\r\n"
		+ "    AND warehouse =?4\r\n"
		+ "     GROUP BY \r\n"
		+ "        partno, partdesc, sku\r\n"
		+ "    ) s\r\n"
		+ "JOIN \r\n"
		+ "    material m\r\n"
		+ "ON \r\n"
		+ "    s.partno = m.partno\r\n"
		+ "WHERE \r\n"
		+ "     m.orgid =?1\r\n"
		+ "    AND m.client =?3\r\n"
		+ "    AND m.branchcode =?2\r\n"
		+ "    AND m.warehouse =?4\r\n"
		+ "    AND s.total_sqtyt <= m.lowqty\r\n"
		,nativeQuery =true)
Set<Object[]> getStock(Long orgId,String branchCode, String client, String warehouse);

@Query(nativeQuery =true,value ="SELECT \r\n"
		+ "DATE(docdate) AS orderdate,\r\n"
		+ "COUNT(*) AS ordercount\r\n"
		+ "FROM  putaway\r\n"
		+ "WHERE \r\n"
		+ "DATE(docdate) = CURDATE() and orgid=?1 and branchcode=?2 and client=?3 and warehouse=?4\r\n"
		+ "GROUP BY \r\n"
		+ "DATE(docdate)")
Set<Object[]> getPutAway(Long orgId, String branchCode, String client, String warehouse);

@Query(value ="select partno,PARTDESC,SKU,STATUS,BATCH,sum(sqty) as availqty from stockdetails\r\n"
		+ " where orgid=?1 and warehouse=?4 and branchcode=?2 and client=?3 AND BIN=?5\r\n"
		+ "  group by partno,PARTDESC,SKU,STATUS,BATCH HAVING sum(sqty) > 0",nativeQuery =true)
Set<Object[]> getBinDetails3(Long orgId, String branchCode, String client, String warehouse,String bin);

@Query(value ="select w.rowno,w.level,W.bin from warehouselocationdetails w where orgid=?1  AND \r\n"
		+ " branchcode=?2 AND warehouse=?3 GROUP BY w.rowno,w.level,W.bin ORDER BY W.ROWNO,W.bin",nativeQuery =true)
Set<Object[]> getStorageDetails2(Long orgId, String branchCode, String warehouse);


@Query(nativeQuery =true,value ="select count(*) from(\r\n"
		+ "SELECT \r\n"
		+ "    b.entryno, \r\n"
		+ "    b.entrydate, \r\n"
		+ "    SUM(b.totalgrnqty) AS qty, \r\n"
		+ "    'Complete' AS status\r\n"
		+ "FROM grn b \r\n"
		+ "WHERE b.orgid = ?1\r\n"
		+ "  AND b.finyear = ?5 \r\n"
		+ "  AND b.branchcode = ?2\r\n"
		+ "  AND b.client = ?4\r\n"
		+ "  AND b.warehouse = ?3\r\n"
		+ "  AND (MONTH(b.docdate) = ?6 OR ?6 IS NULL)\r\n"
		+ "GROUP BY b.entryno, b.entrydate\r\n"
		+ "UNION\r\n"
		+ "SELECT \r\n"
		+ "    a.entryno, \r\n"
		+ "    a.entrydate, \r\n"
		+ "    sum((a.recqty-a.damageqty)) AS qty, \r\n"
		+ "    'Pending' AS status \r\n"
		+ "FROM grnexcelupload a \r\n"
		+ "WHERE a.orgid = ?1\r\n"
		+ "  AND a.finyear = ?5\r\n"
		+ "  AND a.branchcode = ?2\r\n"
		+ "  AND a.warehouse = ?3\r\n"
		+ "  AND a.client = ?4\r\n"
		+ "  AND (MONTH(a.entrydate) = ?6 OR ?6 IS NULL)\r\n"
		+ "  AND a.entryno NOT IN (\r\n"
		+ "      SELECT b.entryno \r\n"
		+ "      FROM grn b \r\n"
		+ "      WHERE b.orgid = ?1\r\n"
		+ "        AND b.finyear = ?5\r\n"
		+ "        AND b.branchcode = ?2\r\n"
		+ "        AND b.client = ?4\r\n"
		+ "  )\r\n"
		+ "GROUP BY a.entryno, a.entrydate)z")
Set<Object[]> getGrnOrderDetailsPerIn(Long orgId, String branchCode, String warehouse, String client,
		 int finYear, String month);


@Query(nativeQuery =true,value ="SELECT A.rowno,A.levelno,A.bin,B.binstatus FROM vw_clientbindetails A,wv_locationstatus B where\r\n"
		+ "  A.orgid =B.ORGID\r\n"
		+ "  AND A.BIN=B.BIN\r\n"
		+ "  AND A.warehouse =B.WAREHOUSE\r\n"
		+ "  AND A.branchcode =B.branchcode\r\n"
		+ "  AND A.client =B.client AND\r\n"
		+ "  A.orgid =?1\r\n"
		+ "  AND A.warehouse =?4\r\n"
		+ "  AND A.branchcode =?2\r\n"
		+ "  AND A.client =?3 \r\n"
		+ " group by A.rowno,A.levelno,A.bin,B.binstatus ORDER BY A.ROWNO,A.bin")
Set<Object[]> getBinDetailsForClient(Long orgId, String branchCode, String client, String warehouse);

@Query(value ="select count(*) from(\r\n"
		+ "SELECT \r\n"
		+ "    b.entryno, \r\n"
		+ "    b.entrydate, \r\n"
		+ "    SUM(b.totalgrnqty) AS qty, \r\n"
		+ "    'Complete' AS status\r\n"
		+ "FROM grn b \r\n"
		+ "WHERE b.orgid = ?1\r\n"
		+ "  AND b.finyear = ?5 \r\n"
		+ "  AND b.branchcode = ?2\r\n"
		+ "  AND b.client = ?4\r\n"
		+ "  AND b.warehouse = ?3\r\n"
		+ "GROUP BY b.entryno, b.entrydate\r\n"
		+ "UNION\r\n"
		+ "SELECT \r\n"
		+ "    a.entryno, \r\n"
		+ "    a.entrydate, \r\n"
		+ "    sum((a.recqty-a.damageqty)) AS qty, \r\n"
		+ "    'Pending' AS status \r\n"
		+ "FROM grnexcelupload a \r\n"
		+ "WHERE a.orgid = ?1\r\n"
		+ "  AND a.finyear = ?5\r\n"
		+ "  AND a.branchcode = ?2\r\n"
		+ "  AND a.warehouse = ?3\r\n"
		+ "  AND a.client = ?4\r\n"
		+ "  AND a.entryno NOT IN (\r\n"
		+ "      SELECT b.entryno \r\n"
		+ "      FROM grn b \r\n"
		+ "      WHERE b.orgid = ?1\r\n"
		+ "        AND b.finyear = ?5\r\n"
		+ "        AND b.branchcode = ?2\r\n"
		+ "        AND b.client = ?4\r\n"
		+ "  )\r\n"
		+ "GROUP BY a.entryno, a.entrydate)z",nativeQuery=true)
Set<Object[]> getGrnOrderDetails(Long orgId, String branchCode, String warehouse, String client, int finYear);

@Query(nativeQuery =true,value ="SELECT count(*) \r\n"
		+ "FROM (\r\n"
		+ "    SELECT \r\n"
		+ "        b.orderno, \r\n"
		+ "        b.orderdate, \r\n"
		+ "        SUM(b.totalorderqty) AS qty, \r\n"
		+ "        'Complete' AS status\r\n"
		+ "    FROM buyerorder b \r\n"
		+ "    WHERE b.orgid = ?1  -- Set this to 1000000001\r\n"
		+ "      AND b.finyear = ?5 -- Set this to '2024'\r\n"
		+ "      AND b.branchcode = ?2 -- Set this to 'BLRW'\r\n"
		+ "      AND b.client = ?4 -- Set this to 'BACARDI'\r\n"
		+"AND (MONTH(B.DOCDATE) = ?6 OR ?6 IS NULL)\r\n"
		+ "    GROUP BY b.orderno, b.orderdate \r\n"
		+ "\r\n"
		+ "    UNION\r\n"
		+ "\r\n"
		+ "    SELECT \r\n"
		+ "        a.orderno, \r\n"
		+ "        a.orderdate, \r\n"
		+ "        SUM(a.qty) AS qty, \r\n"
		+ "        'Pending' AS status \r\n"
		+ "    FROM boexcelupload a \r\n"
		+ "    WHERE a.orgid = ?1  -- Set this to 1000000001\r\n"
		+ "      AND a.finyear = ?5  -- Set this to '2024'\r\n"
		+ "      AND a.branchcode = ?2  -- Set this to 'BLRW'\r\n"
		+ "      AND a.warehouse = ?3  -- Set this to 'BLRWAREHOUSE'\r\n"
		+ "      AND a.client = ?4  -- Set this to 'BACARDI'\r\n"
		+ "      AND (MONTH(a.orderdate) = ?6 OR ?6 IS NULL) -- Set this to NULL or a specific month\r\n"
		+ "      AND a.orderno NOT IN (\r\n"
		+ "          SELECT b.orderno \r\n"
		+ "          FROM buyerorder b \r\n"
		+ "          WHERE b.orgid = ?1\r\n"
		+ "            AND b.finyear = ?5\r\n"
		+ "            AND b.branchcode = ?2\r\n"
		+ "            AND b.client = ?4\r\n"
		+ "      )\r\n"
		+ "    GROUP BY a.orderno, a.orderdate\r\n"
		+ ") z\r\n")
Set<Object[]> getOutBoundOrderPerMonth1(Long orgId, String branchCode, String warehouse, String client,
		int finYear, String month);

@Query(value ="SELECT count(*) \r\n"
		+ "FROM (\r\n"
		+ "    SELECT \r\n"
		+ "        b.orderno, \r\n"
		+ "        b.orderdate, \r\n"
		+ "        SUM(b.totalorderqty) AS qty, \r\n"
		+ "        'Complete' AS status\r\n"
		+ "    FROM buyerorder b \r\n"
		+ "    WHERE b.orgid = ?1  -- Set this to 1000000001\r\n"
		+ "      AND b.finyear = ?5 -- Set this to '2024'\r\n"
		+ "      AND b.branchcode = ?2 -- Set this to 'BLRW'\r\n"
		+ "      AND b.client = ?4 -- Set this to 'BACARDI'\r\n"
		+ "    GROUP BY b.orderno, b.orderdate \r\n"
		+ "\r\n"
		+ "    UNION\r\n"
		+ "\r\n"
		+ "    SELECT \r\n"
		+ "        a.orderno, \r\n"
		+ "        a.orderdate, \r\n"
		+ "        SUM(a.qty) AS qty, \r\n"
		+ "        'Pending' AS status \r\n"
		+ "    FROM boexcelupload a \r\n"
		+ "    WHERE a.orgid = ?1  -- Set this to 1000000001\r\n"
		+ "      AND a.finyear = ?5  -- Set this to '2024'\r\n"
		+ "      AND a.branchcode = ?2  -- Set this to 'BLRW'\r\n"
		+ "      AND a.warehouse = ?3  -- Set this to 'BLRWAREHOUSE'\r\n"
		+ "      AND a.client = ?4  -- Set this to 'BACARDI'\r\n"
		+ "      AND a.orderno NOT IN (\r\n"
		+ "          SELECT b.orderno \r\n"
		+ "          FROM buyerorder b \r\n"
		+ "          WHERE b.orgid = ?1\r\n"
		+ "            AND b.finyear = ?5\r\n"
		+ "            AND b.branchcode = ?2\r\n"
		+ "            AND b.client = ?4\r\n"
		+ "      )\r\n"
		+ "    GROUP BY a.orderno, a.orderdate\r\n"
		+ ") z",nativeQuery=true)
Set<Object[]> getOutBoundOrderPerYear1(Long orgId, String branchCode, String warehouse, String client, int finYear);

@Query(nativeQuery =true,value ="SELECT \r\n"
		+ "    A.PARTNO,\r\n"
		+ "    A.PARTDESC,\r\n"
		+ "    A.SKU,\r\n"
		+ "    A.bin,\r\n"
		+ "    A.grnno,\r\n"
		+ "    A.grndate,\r\n"
		+ "    A.expdate,\r\n"
		+ "    SUM(A.SQTY) AS holdQty \r\n"
		+ "FROM \r\n"
		+ "    (SELECT \r\n"
		+ "         partno,\r\n"
		+ "         partdesc,\r\n"
		+ "         sku,\r\n"
		+ "         grnno,\r\n"
		+ "         grndate,\r\n"
		+ "         batch,\r\n"
		+ "         batchdate,\r\n"
		+ "         expdate,\r\n"
		+ "         bin,\r\n"
		+ "         SUM(sqty) AS SQTY \r\n"
		+ "     FROM \r\n"
		+ "         stockdetails \r\n"
		+ "     WHERE \r\n"
		+ "         orgid =?1\r\n"
		+ "         AND warehouse =?3 \r\n"
		+ "         AND branchcode =?2\r\n"
		+ "         AND client =?4\r\n"
		+ "         AND status in ( 'H','D') \r\n"
		+ "     GROUP BY \r\n"
		+ "         partno, partdesc, sku, grnno, grndate, batch, batchdate, expdate, bin \r\n"
		+ "     HAVING \r\n"
		+ "         SUM(sqty) > 0\r\n"
		+ "    ) A \r\n"
		+ "GROUP BY \r\n"
		+ "A.PARTNO,\r\n"
		+ "    A.PARTDESC,\r\n"
		+ "    A.SKU,\r\n"
		+ "    A.bin,\r\n"
		+ "    A.grnno,\r\n"
		+ "    A.grndate,\r\n"
		+ "    A.expdate")
Set<Object[]> getHoldMaterialCount1(Long orgId, String branchCode, String warehouse, String client);

@Query(nativeQuery =true,value ="select bin,binstatus from wv_locationstatus where orgid=?1 and branchcode=?2 and client=?3\r\n"
		+ "and warehouse=?4 group by bin,binstatus order by bin")
Set<Object[]> getBinDetailsClientWiseForEmpty(Long orgId, String branchCode, String client, String warehouse);


@Query(nativeQuery =true,value ="SELECT \r\n"
		+ "    partno,\r\n"
		+ "    partdesc,\r\n"
		+ "    sku,\r\n"
		+ "    batch,\r\n"
		+ "    batchdate,\r\n"
		+ "    grnno,\r\n"
		+ "    grndate,\r\n"
		+ "    expdate,\r\n"
		+ "    SUM(sqty) AS total_quantity,\r\n"
		+ "    DATEDIFF(expdate, CURDATE()) AS days_until_expiration,\r\n"
		+ "    bin\r\n"
		+ "FROM \r\n"
		+ "    stockdetails\r\n"
		+ "WHERE \r\n"
		+ "    orgid =?1\r\n"
		+ "    AND branchcode =?2\r\n"
		+ "    AND client =?3\r\n"
		+ "    AND warehouse =?4\r\n"
		+ "    AND DATEDIFF(expdate, CURDATE()) < 20\r\n"
		+ "GROUP BY \r\n"
		+ "    partno,\r\n"
		+ "    partdesc,\r\n"
		+ "    sku,\r\n"
		+ "    batch,\r\n"
		+ "    batchdate,\r\n"
		+ "    grnno,\r\n"
		+ "    grndate,\r\n"
		+ "    expdate,\r\n"
		+ "    bin\r\n"
		+ "    having  SUM(sqty)>0\r\n"
		+ "ORDER BY \r\n"
		+ "    days_until_expiration DESC,\r\n"
		+ "    bin")
Set<Object[]> getExpDetailsForMaterials(Long orgId, String branchCode, String client, String warehouse);

@Query(nativeQuery =true,value ="SELECT \r\n"
		+ "DATE(docdate) AS orderdate,\r\n"
		+ "COUNT(*) AS ordercount\r\n"
		+ "FROM  pickrequest\r\n"
		+ "WHERE \r\n"
		+ "DATE(docdate) = CURDATE() and orgid=?1 and branchcode=?2 and client=?3  and warehouse=?4\r\n"
		+ "GROUP BY \r\n"
		+ "DATE(docdate)")
Set<Object[]> getPickRequest(Long orgId, String branchCode, String client, String warehouse);

List<StockDetailsVO> findByOrgIdAndBranchAndBranchCodeAndClient(Long orgid, String branch, String branch2,
		String client);

@Query(nativeQuery = true,value = "select case when stockfreeze=1 then 'true' else 'false' end freezestatus from stockdetails where orgid=?1 and branch=?2  and branchcode=?3 and client=?4  group by stockfreeze")
boolean getStockFreezeStatus(Long orgId, String branch, String branchCode, String client);

StockDetailsVO findByRefNoAndPartnoAndSourceScreenCode(String docId, String partNo, String screenCode);

@Query(nativeQuery =true,value ="select m.client,m.partno,m.partdesc,m.sku,m.criticalstocklevel,sum(s.sqty) as qty from material m inner join stockdetails s on m.partno = s.partno and m.client = s.client and m.orgid = s.orgid where m.orgid =?1 and m.branchcode =?2\r\n"
		+ "  and m.client =?3 and m.warehouse =?4 group by m.client,m.partno,m.partdesc,m.sku,m.criticalstocklevel having SUM(s.sqty) <= m.criticalstocklevel")
Set<Object[]> getCriticalStockLevelDetails(Long orgId, String branchCode, String client, String warehouse);

@Query(nativeQuery = true, value = "select sum(today) today,sum(yesterday) yesterday,sum(thisweek) thisweek,sum(thismonth) thismonth from (\r\n"
		+ "select  coalesce(SUM(a.sqty), 0) as today,0 yesterday,0 thisweek,0 thismonth  from  stockdetails a where  a.orgid =?1 and a.branchcode =?2\r\n"
		+ "and a.warehouse =?3 and a.finyear =?4 and a.client =?5 and date(a.stockdate) = curdate()\r\n"
		+ "union\r\n"
		+ "select  0 as today,coalesce(SUM(a.sqty), 0) yesterday,0 thisweek,0 thismonth  from  stockdetails a where  a.orgid =?1 and a.branchcode =?2\r\n"
		+ "and a.warehouse =?3 and a.finyear =?4 and a.client =?5 and date(a.stockdate) = curdate() - interval 1 day\r\n"
		+ "union \r\n"
		+ "select  0 as today,0 yesterday,coalesce(SUM(a.sqty), 0) thisweek,0 thismonth  from  stockdetails a where  a.orgid =?1 and a.branchcode =?2\r\n"
		+ "and a.warehouse =?3 and a.finyear =?4 and a.client =?5 and date(a.stockdate) between date_sub(curdate(), interval weekday(curdate()) day)\r\n"
		+ "and date_add(date_sub(curdate(), interval weekday(curdate()) day), interval 6 day)\r\n"
		+ "union\r\n"
		+ "select  0 as today,0 yesterday, 0 thisweek,coalesce(SUM(a.sqty), 0) thismonth  from  stockdetails a where  a.orgid =?1 and a.branchcode =?2\r\n"
		+ "and a.warehouse =?3 and a.finyear =?4 and a.client =?5 and month(a.stockdate)=month(curdate())	\r\n"
		+ ") a ")
Set<Object[]> getDashBoardStockDetailsReport(Long orgId, String branchCode, String warehouse, Long finYear,
		String client);

@Query(nativeQuery = true, value = "SELECT\r\n"
		+ "    s.partno,\r\n"
		+ "    MAX(s.partdesc) AS partdesc,\r\n"
		+ "    SUM(s.sqty) AS total_qty,\r\n"
		+ "    MAX(s.expdate) AS expdate,\r\n"
		+ "    MAX(s.status) AS status,\r\n"
		+ "    pr.last_sale_date,\r\n"
		+ "    DATEDIFF(CURDATE(), pr.last_sale_date) AS days_since_sale\r\n"
		+ "FROM stockdetails s\r\n"
		+ "LEFT JOIN\r\n"
		+ "(\r\n"
		+ "    SELECT\r\n"
		+ "        partno,\r\n"
		+ "        MAX(stockdate) AS last_sale_date\r\n"
		+ "    FROM stockdetails\r\n"
		+ "    WHERE sourcescreencode = 'PR'\r\n"
		+ "    GROUP BY partno\r\n"
		+ ") pr\r\n"
		+ "ON pr.partno = s.partno\r\n"
		+ "WHERE s.client = ?4\r\n"
		+ "  AND s.warehouse = ?3\r\n"
		+ "  AND s.orgid = ?1\r\n"
		+ "  AND s.branchcode = ?2\r\n"
		+ "  AND s.status = 'R'\r\n"
		+ "GROUP BY\r\n"
		+ "    s.partno,\r\n"
		+ "    pr.last_sale_date\r\n"
		+ "HAVING\r\n"
		+ "    SUM(s.sqty) > 0\r\n"
		+ "    AND (\r\n"
		+ "        pr.last_sale_date IS NULL\r\n"
		+ "        OR DATEDIFF(CURDATE(), pr.last_sale_date) > 20\r\n"
		+ "    )\r\n"
		+ "ORDER BY\r\n"
		+ "    days_since_sale DESC")
Set<Object[]> getSlowMoveStockDetailsReport(Long orgId, String branchCode, String warehouse, String client);

@Query(nativeQuery = true, value = "SELECT\r\n"
		+ "    s.partno,\r\n"
		+ "    MAX(s.partdesc) AS partdesc,\r\n"
		+ "    SUM(s.sqty) AS total_qty,\r\n"
		+ "    MAX(s.expdate) AS expdate,\r\n"
		+ "    MAX(s.status) AS status,\r\n"
		+ "    pr.last_sale_date,\r\n"
		+ "    DATEDIFF(CURDATE(), pr.last_sale_date) AS days_since_sale\r\n"
		+ "FROM stockdetails s\r\n"
		+ "LEFT JOIN\r\n"
		+ "(\r\n"
		+ "    SELECT\r\n"
		+ "        partno,\r\n"
		+ "        MAX(stockdate) AS last_sale_date\r\n"
		+ "    FROM stockdetails\r\n"
		+ "    WHERE sourcescreencode = 'PR'\r\n"
		+ "    GROUP BY partno\r\n"
		+ ") pr\r\n"
		+ "ON pr.partno = s.partno\r\n"
		+ "WHERE s.client = ?4\r\n"
		+ "  AND s.warehouse = ?3\r\n"
		+ "  AND s.orgid = ?1\r\n"
		+ "  AND s.branchcode = ?2\r\n"
		+ "  AND s.status = 'R'\r\n"
		+ "GROUP BY\r\n"
		+ "    s.partno,\r\n"
		+ "    pr.last_sale_date\r\n"
		+ "HAVING\r\n"
		+ "    SUM(s.sqty) > 0\r\n"
		+ "    AND (\r\n"
		+ "        pr.last_sale_date IS NULL\r\n"
		+ "        OR DATEDIFF(CURDATE(), pr.last_sale_date) > 60\r\n"
		+ "    )\r\n"
		+ "ORDER BY\r\n"
		+ "    days_since_sale DESC")
Set<Object[]> getDeadStockStockDetailsReport(Long orgId, String branchCode, String warehouse, String client);

@Query(nativeQuery = true,value = "SELECT\r\n"
		+ "    partno,\r\n"
		+ "    partdesc,\r\n"
		+ "    batch,\r\n"
		+ "    status,\r\n"
		+ "    expdate,\r\n"
		+ "    SUM(sqty) AS sqty\r\n"
		+ "FROM stockdetails\r\n"
		+ "WHERE status = 'R'\r\n"
		+ "  AND expdate < CURDATE()\r\n"
		+ "  AND client = ?4 \r\n"
		+ "  AND warehouse = ?3 \r\n"
		+ "  AND orgid = ?1 \r\n"
		+ "  AND branchcode = ?2 \r\n"
		+ "GROUP BY\r\n"
		+ "    partno,\r\n"
		+ "    partdesc,\r\n"
		+ "    batch,\r\n"
		+ "    status,\r\n"
		+ "    expdate\r\n"
		+ "HAVING SUM(sqty) > 0")
Set<Object[]> getExpiredItemStockDetailsReport(Long orgId, String branchCode, String warehouse, String client);

@Query(nativeQuery =true,value ="select m.client,m.partno,m.partdesc,m.sku,m.maximumqty,sum(s.sqty) as qty from material m inner join stockdetails s on m.partno = s.partno and m.client = s.client and m.orgid = s.orgid where m.orgid =?1 and m.branchcode =?2\r\n"
		+ "	  and m.client =?3 and m.warehouse =?4 group by m.client,m.partno,m.partdesc,m.sku,m.maximumqty having SUM(s.sqty) > m.maximumqty")
Set<Object[]> getMaximumStockLevelDetails(Long orgId, String branchCode, String client, String warehouse);

//@Query(nativeQuery =true,value ="select 'Expired Inventory' as type,'Expired Stock Still Available' as description, ?4 as warehouse  ,count(*) as totalcount from (select partno,partdesc,batch,status,expdate,SUM(sqty) AS sqty from stockdetails where orgid=?1 and branchcode=?2 and status = 'R' and expdate < CURDATE() and warehouse=?4 and\r\n"
//		+ "client=?3 group by partno,partdesc,batch,status,expdate  having  sum(sqty)>0) t\r\n"
//		+ "union \r\n"
//		+ "select 'Near Expiry Inventory' as type,'Items Approaching Expiry' as description, ?4 as warehouse  ,count(*) as totalcount from ( select partno,partdesc,sku,batch,batchdate,grnno,grndate,expdate,SUM(sqty) AS total_quantity,DATEDIFF(expdate, CURDATE()) AS days_until_expiration,\r\n"
//		+ "bin from stockdetails where orgid =?1 and branchcode =?2 and client =?3 and warehouse =?4 and DATEDIFF(expdate, CURDATE()) < 20\r\n"
//		+ "group by partno,partdesc,sku,batch,batchdate,grnno,grndate,expdate,bin having  SUM(sqty)>0 order by days_until_expiration desc,bin)t\r\n"
//		+ "union\r\n"
//		+ "select 'Blocked Stock Report' as type,'QC Hold/Damaged Stock Exceeds Threshold Limits' as description, ?4 as warehouse  ,count(*) as totalcount from (select partno,partdesc,sku,grnno,grndate,batch,batchdate,expdate,bin,sum(sqty) as SQTY from stockdetails where orgid =?1 and warehouse =?4 \r\n"
//		+ "and  branchcode =?2 and client =?3 and status in ( 'H','D') group by partno, partdesc, sku, grnno, grndate, batch, batchdate, expdate, bin \r\n"
//		+ "having sum(sqty) > 0) t\r\n"
//		+ "union\r\n"
//		+ " select 'Slow Moving Inventory' as type,'No Moment for X days' as description, ?4 as warehouse  ,count(*) as totalcount from\r\n"
//		+ "    (select s.partno,MAX(s.partdesc) AS partdesc,SUM(s.sqty) AS total_qty,MAX(s.expdate) AS expdate,MAX(s.status) AS status,pr.last_sale_date,DATEDIFF(CURDATE(), pr.last_sale_date) AS days_since_sale\r\n"
//		+ "from stockdetails s left join(select partno,MAX(stockdate) AS last_sale_date from stockdetails where sourcescreencode = 'PR'group by partno) pr\r\n"
//		+ "on pr.partno = s.partno where s.client = ?3 and s.warehouse =?4 and s.orgid =?1 and s.branchcode = ?2\r\n"
//		+ "and s.status = 'R'group by s.partno,pr.last_sale_date having sum(s.sqty) > 0\r\n"
//		+ "and (pr.last_sale_date IS NULL OR DATEDIFF(CURDATE(), pr.last_sale_date) > 20) order by\r\n"
//		+ "		    days_since_sale desc)t\r\n"
//		+ "	union\r\n"
//		+ "    select 'Dead Stock Report' as type,'No Moment for Y Months' as description, ?4 as warehouse  ,count(*) as totalcount from\r\n"
//		+ "    (select s.partno,MAX(s.partdesc) AS partdesc,SUM(s.sqty) AS total_qty,MAX(s.expdate) AS expdate,MAX(s.status) AS status,pr.last_sale_date,\r\n"
//		+ "DATEDIFF(CURDATE(), pr.last_sale_date) AS days_since_sale from stockdetails s left join(select partno,MAX(stockdate) AS last_sale_date\r\n"
//		+ "from stockdetails where sourcescreencode = 'PR'group by  partno) pr on pr.partno = s.partno where s.client = ?3\r\n"
//		+ "and s.warehouse = ?4 and s.orgid =?1 and s.branchcode =?2 and s.status = 'R'group by \r\n"
//		+ "	s.partno,pr.last_sale_date having SUM(s.sqty) > 0 and (\r\n"
//		+ "		        pr.last_sale_date IS NULL\r\n"
//		+ "		        OR DATEDIFF(CURDATE(), pr.last_sale_date) > 60\r\n"
//		+ "		    )\r\n"
//		+ "		ORDER BY\r\n"
//		+ "		    days_since_sale DESC)t\r\n"
//		+ "            union\r\n"
//		+ "select 'Low Stock Alert' as type,'Stock Below Minimum Level' as description, ?4 as warehouse  ,count(*) as totalcount from ( select m.client,m.partno,m.partdesc,m.sku,m.criticalstocklevel,sum(s.sqty) as qty from material m inner join stockdetails s on m.partno = s.partno and m.client = s.client and m.orgid = s.orgid where m.orgid =?1 and m.branchcode =?2\r\n"
//		+ "	and m.client =?3 and m.warehouse =?4 group by m.client,m.partno,m.partdesc,m.sku,m.criticalstocklevel having SUM(s.sqty) <= m.criticalstocklevel)t\r\n"
//		+ " union\r\n"
//		+ "select 'Over Stock Alert' as type,'Inventory Exceeds Maximum Level' as description, ?4 as warehouse  ,count(*) as totalcount from (\r\n"
//		+ " select m.client,m.partno,m.partdesc,m.sku,m.maximumqty, SUM(s.sqty) as qty from material m inner join stockdetails s on m.partno = s.partno and m.client = s.client\r\n"
//		+ " and m.orgid = s.orgid where m.orgid =?1 and m.branchcode =?2\r\n"
//		+ " and m.client =?3 and m.warehouse =?4 group by m.client,m.partno,m.partdesc,m.sku,m.maximumqty having SUM(s.sqty) > m.maximumqty)t")
//Set<Object[]> getEscalationDetails(Long orgId, String branchCode, String client, String warehouse);

@Query(nativeQuery =true,value ="SELECT\r\n"
		+ "    sno,\r\n"
		+ "    type,\r\n"
		+ "    description,\r\n"
		+ "    warehouse,\r\n"
		+ "    totalcount,\r\n"
		+ "    severity,\r\n"
		+ "    Critical,\r\n"
		+ "    High,\r\n"
		+ "    Medium,\r\n"
		+ "    Low,\r\n"
		+ "    TotalEscalations\r\n"
		+ "FROM\r\n"
		+ "(\r\n"
		+ "\r\n"
		+ "    SELECT\r\n"
		+ "        1 AS sno,\r\n"
		+ "        NULL AS type,\r\n"
		+ "        NULL AS description,\r\n"
		+ "        NULL AS warehouse,\r\n"
		+ "        NULL AS totalcount,\r\n"
		+ "        NULL AS severity,\r\n"
		+ "        SUM(CASE WHEN severity='Critical' THEN totalcount ELSE 0 END) AS Critical,\r\n"
		+ "        SUM(CASE WHEN severity='High' THEN totalcount ELSE 0 END) AS High,\r\n"
		+ "        SUM(CASE WHEN severity='Medium' THEN totalcount ELSE 0 END) AS Medium,\r\n"
		+ "        SUM(CASE WHEN severity='Low' THEN totalcount ELSE 0 END) AS Low,\r\n"
		+ "        SUM(totalcount) AS TotalEscalations\r\n"
		+ "    FROM\r\n"
		+ "    (\r\n"
		+ "        -- 1. Expired Inventory\r\n"
		+ "        SELECT\r\n"
		+ "            'Expired Inventory' AS type,\r\n"
		+ "            'Expired Stock Still Available' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount,\r\n"
		+ "            'Critical' AS severity\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT partno, partdesc, batch, status, expdate\r\n"
		+ "            FROM stockdetails\r\n"
		+ "            WHERE orgid=?1\r\n"
		+ "              AND branchcode=?2\r\n"
		+ "              AND status='R'\r\n"
		+ "              AND expdate<CURDATE()\r\n"
		+ "              AND warehouse=?4\r\n"
		+ "              AND client=?3\r\n"
		+ "            GROUP BY partno, partdesc, batch, status, expdate\r\n"
		+ "            HAVING SUM(sqty)>0\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "        SELECT\r\n"
		+ "            'Near Expiry Inventory' AS type,\r\n"
		+ "            'Items Approaching Expiry' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount,\r\n"
		+ "            CASE\r\n"
		+ "                WHEN MIN(days)<=5 THEN 'Critical'\r\n"
		+ "                WHEN MIN(days)<=10 THEN 'High'\r\n"
		+ "                WHEN MIN(days)<=20 THEN 'Medium'\r\n"
		+ "                ELSE 'Low'\r\n"
		+ "            END AS severity\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT\r\n"
		+ "                partno,\r\n"
		+ "                DATEDIFF(expdate, CURDATE()) AS days\r\n"
		+ "            FROM stockdetails\r\n"
		+ "            WHERE orgid=?1\r\n"
		+ "              AND branchcode=?2\r\n"
		+ "              AND client=?3\r\n"
		+ "              AND warehouse=?4\r\n"
		+ "            GROUP BY partno, batch, expdate\r\n"
		+ "            HAVING SUM(sqty)>0\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 3. Blocked Stock\r\n"
		+ "        SELECT\r\n"
		+ "            'Blocked Stock Report' AS type,\r\n"
		+ "            'QC Hold/Damaged Stock' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount,\r\n"
		+ "            'High' AS severity\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT partno\r\n"
		+ "            FROM stockdetails\r\n"
		+ "            WHERE orgid=?1\r\n"
		+ "              AND branchcode=?2\r\n"
		+ "              AND warehouse=?4\r\n"
		+ "              AND client=?3\r\n"
		+ "              AND status IN('H','D')\r\n"
		+ "            GROUP BY partno\r\n"
		+ "            HAVING SUM(sqty)>0\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 4. Slow Moving Inventory\r\n"
		+ "        SELECT\r\n"
		+ "            'Slow Moving Inventory' AS type,\r\n"
		+ "            'No Movement for X Days' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount,\r\n"
		+ "            'Medium' AS severity\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT s.partno\r\n"
		+ "            FROM stockdetails s\r\n"
		+ "            LEFT JOIN\r\n"
		+ "            (\r\n"
		+ "                SELECT partno,\r\n"
		+ "                       MAX(stockdate) AS last_sale_date\r\n"
		+ "                FROM stockdetails\r\n"
		+ "                WHERE sourcescreencode='PR'\r\n"
		+ "                GROUP BY partno\r\n"
		+ "            ) p\r\n"
		+ "            ON s.partno=p.partno\r\n"
		+ "            WHERE s.client=?3\r\n"
		+ "              AND s.warehouse=?4\r\n"
		+ "              AND s.orgid=?1\r\n"
		+ "              AND s.branchcode=?2\r\n"
		+ "              AND s.status='R'\r\n"
		+ "            GROUP BY s.partno, p.last_sale_date\r\n"
		+ "            HAVING SUM(s.sqty)>0\r\n"
		+ "               AND (p.last_sale_date IS NULL\r\n"
		+ "                    OR DATEDIFF(CURDATE(), p.last_sale_date)>20)\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 5. Dead Stock\r\n"
		+ "        SELECT\r\n"
		+ "            'Dead Stock Report' AS type,\r\n"
		+ "            'No Movement for Y Months' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount,\r\n"
		+ "            'High' AS severity\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT s.partno\r\n"
		+ "            FROM stockdetails s\r\n"
		+ "            LEFT JOIN\r\n"
		+ "            (\r\n"
		+ "                SELECT partno,\r\n"
		+ "                       MAX(stockdate) AS last_sale_date\r\n"
		+ "                FROM stockdetails\r\n"
		+ "                WHERE sourcescreencode='PR'\r\n"
		+ "                GROUP BY partno\r\n"
		+ "            ) p\r\n"
		+ "            ON s.partno=p.partno\r\n"
		+ "            WHERE s.client=?3\r\n"
		+ "              AND s.warehouse=?4\r\n"
		+ "              AND s.orgid=?1\r\n"
		+ "              AND s.branchcode=?2\r\n"
		+ "              AND s.status='R'\r\n"
		+ "            GROUP BY s.partno, p.last_sale_date\r\n"
		+ "            HAVING SUM(s.sqty)>0\r\n"
		+ "               AND (p.last_sale_date IS NULL\r\n"
		+ "                    OR DATEDIFF(CURDATE(), p.last_sale_date)>60)\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 6. Low Stock Alert\r\n"
		+ "        SELECT\r\n"
		+ "            'Low Stock Alert' AS type,\r\n"
		+ "            'Stock Below Minimum Level' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount,\r\n"
		+ "            'High' AS severity\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT m.partno\r\n"
		+ "            FROM material m\r\n"
		+ "            JOIN stockdetails s\r\n"
		+ "            ON m.partno=s.partno\r\n"
		+ "            AND m.client=s.client\r\n"
		+ "            AND m.orgid=s.orgid\r\n"
		+ "            WHERE m.orgid=?1\r\n"
		+ "              AND m.branchcode=?2\r\n"
		+ "              AND m.client=?3\r\n"
		+ "              AND m.warehouse=?4\r\n"
		+ "            GROUP BY m.partno, m.criticalstocklevel\r\n"
		+ "            HAVING SUM(s.sqty) <= m.criticalstocklevel\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 7. Over Stock Alert\r\n"
		+ "        SELECT\r\n"
		+ "            'Over Stock Alert' AS type,\r\n"
		+ "            'Inventory Exceeds Maximum Level' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount,\r\n"
		+ "            'Medium' AS severity\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT m.partno\r\n"
		+ "            FROM material m\r\n"
		+ "            JOIN stockdetails s\r\n"
		+ "            ON m.partno=s.partno\r\n"
		+ "            AND m.client=s.client\r\n"
		+ "            AND m.orgid=s.orgid\r\n"
		+ "            WHERE m.orgid=?1\r\n"
		+ "              AND m.branchcode=?2\r\n"
		+ "              AND m.client=?3\r\n"
		+ "              AND m.warehouse=?4\r\n"
		+ "            GROUP BY m.partno, m.maximumqty\r\n"
		+ "            HAVING SUM(s.sqty) > m.maximumqty\r\n"
		+ "        ) t\r\n"
		+ "    ) summary_data\r\n"
		+ "\r\n"
		+ "    UNION ALL\r\n"
		+ "\r\n"
		+ "    -- sno=2: Detailed Query\r\n"
		+ "    SELECT\r\n"
		+ "        2 AS sno,\r\n"
		+ "        type,\r\n"
		+ "        description,\r\n"
		+ "        warehouse,\r\n"
		+ "        totalcount,\r\n"
		+ "        NULL AS severity,\r\n"
		+ "        NULL AS Critical,\r\n"
		+ "        NULL AS High,\r\n"
		+ "        NULL AS Medium,\r\n"
		+ "        NULL AS Low,\r\n"
		+ "        NULL AS TotalEscalations\r\n"
		+ "    FROM\r\n"
		+ "    (\r\n"
		+ "        -- 1. Expired Inventory Details\r\n"
		+ "        SELECT\r\n"
		+ "            'Expired Inventory' AS type,\r\n"
		+ "            'Expired Stock Still Available' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT partno, partdesc, batch, status, expdate, SUM(sqty) AS sqty\r\n"
		+ "            FROM stockdetails\r\n"
		+ "            WHERE orgid=?1\r\n"
		+ "              AND branchcode=?2\r\n"
		+ "              AND status='R'\r\n"
		+ "              AND expdate<CURDATE()\r\n"
		+ "              AND warehouse=?4\r\n"
		+ "              AND client=?3\r\n"
		+ "            GROUP BY partno, partdesc, batch, status, expdate\r\n"
		+ "            HAVING SUM(sqty)>0\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 2. Near Expiry Inventory Details\r\n"
		+ "        SELECT\r\n"
		+ "            'Near Expiry Inventory' AS type,\r\n"
		+ "            'Items Approaching Expiry' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT\r\n"
		+ "                partno, partdesc, sku, batch, batchdate, grnno, grndate,\r\n"
		+ "                expdate, SUM(sqty) AS total_quantity,\r\n"
		+ "                DATEDIFF(expdate, CURDATE()) AS days_until_expiration,\r\n"
		+ "                bin\r\n"
		+ "            FROM stockdetails\r\n"
		+ "            WHERE orgid=?1\r\n"
		+ "              AND branchcode=?2\r\n"
		+ "              AND client=?3\r\n"
		+ "              AND warehouse=?4\r\n"
		+ "              AND DATEDIFF(expdate, CURDATE()) < 20\r\n"
		+ "            GROUP BY partno, partdesc, sku, batch, batchdate, grnno, grndate, expdate, bin\r\n"
		+ "            HAVING SUM(sqty)>0\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 3. Blocked Stock Details\r\n"
		+ "        SELECT\r\n"
		+ "            'Blocked Stock Report' AS type,\r\n"
		+ "            'QC Hold/Damaged Stock Exceeds Threshold Limits' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT\r\n"
		+ "                partno, partdesc, sku, grnno, grndate, batch, batchdate,\r\n"
		+ "                expdate, bin, SUM(sqty) AS SQTY\r\n"
		+ "            FROM stockdetails\r\n"
		+ "            WHERE orgid=?1\r\n"
		+ "              AND warehouse=?4\r\n"
		+ "              AND branchcode=?2\r\n"
		+ "              AND client=?3\r\n"
		+ "              AND status IN('H','D')\r\n"
		+ "            GROUP BY partno, partdesc, sku, grnno, grndate, batch, batchdate, expdate, bin\r\n"
		+ "            HAVING SUM(sqty)>0\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 4. Slow Moving Inventory Details\r\n"
		+ "        SELECT\r\n"
		+ "            'Slow Moving Inventory' AS type,\r\n"
		+ "            'No Movement for X days' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT\r\n"
		+ "                s.partno,\r\n"
		+ "                MAX(s.partdesc) AS partdesc,\r\n"
		+ "                SUM(s.sqty) AS total_qty,\r\n"
		+ "                MAX(s.expdate) AS expdate,\r\n"
		+ "                MAX(s.status) AS status,\r\n"
		+ "                pr.last_sale_date,\r\n"
		+ "                DATEDIFF(CURDATE(), pr.last_sale_date) AS days_since_sale\r\n"
		+ "            FROM stockdetails s\r\n"
		+ "            LEFT JOIN\r\n"
		+ "            (\r\n"
		+ "                SELECT partno, MAX(stockdate) AS last_sale_date\r\n"
		+ "                FROM stockdetails\r\n"
		+ "                WHERE sourcescreencode='PR'\r\n"
		+ "                GROUP BY partno\r\n"
		+ "            ) pr\r\n"
		+ "            ON pr.partno = s.partno\r\n"
		+ "            WHERE s.client=?3\r\n"
		+ "              AND s.warehouse=?4\r\n"
		+ "              AND s.orgid=?1\r\n"
		+ "              AND s.branchcode=?2\r\n"
		+ "              AND s.status='R'\r\n"
		+ "            GROUP BY s.partno, pr.last_sale_date\r\n"
		+ "            HAVING SUM(s.sqty)>0\r\n"
		+ "               AND (pr.last_sale_date IS NULL\r\n"
		+ "                    OR DATEDIFF(CURDATE(), pr.last_sale_date) > 20)\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 5. Dead Stock Details\r\n"
		+ "        SELECT\r\n"
		+ "            'Dead Stock Report' AS type,\r\n"
		+ "            'No Movement for Y Months' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT\r\n"
		+ "                s.partno,\r\n"
		+ "                MAX(s.partdesc) AS partdesc,\r\n"
		+ "                SUM(s.sqty) AS total_qty,\r\n"
		+ "                MAX(s.expdate) AS expdate,\r\n"
		+ "                MAX(s.status) AS status,\r\n"
		+ "                pr.last_sale_date,\r\n"
		+ "                DATEDIFF(CURDATE(), pr.last_sale_date) AS days_since_sale\r\n"
		+ "            FROM stockdetails s\r\n"
		+ "            LEFT JOIN\r\n"
		+ "            (\r\n"
		+ "                SELECT partno, MAX(stockdate) AS last_sale_date\r\n"
		+ "                FROM stockdetails\r\n"
		+ "                WHERE sourcescreencode='PR'\r\n"
		+ "                GROUP BY partno\r\n"
		+ "            ) pr\r\n"
		+ "            ON pr.partno = s.partno\r\n"
		+ "            WHERE s.client=?3\r\n"
		+ "              AND s.warehouse=?4\r\n"
		+ "              AND s.orgid=?1\r\n"
		+ "              AND s.branchcode=?2\r\n"
		+ "              AND s.status='R'\r\n"
		+ "            GROUP BY s.partno, pr.last_sale_date\r\n"
		+ "            HAVING SUM(s.sqty)>0\r\n"
		+ "               AND (pr.last_sale_date IS NULL\r\n"
		+ "                    OR DATEDIFF(CURDATE(), pr.last_sale_date) > 60)\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "\r\n"
		+ "        -- 6. Low Stock Alert Details\r\n"
		+ "        SELECT\r\n"
		+ "            'Low Stock Alert' AS type,\r\n"
		+ "            'Stock Below Minimum Level' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT\r\n"
		+ "                m.client, m.partno, m.partdesc, m.sku,\r\n"
		+ "                m.criticalstocklevel, SUM(s.sqty) AS qty\r\n"
		+ "            FROM material m\r\n"
		+ "            INNER JOIN stockdetails s\r\n"
		+ "            ON m.partno=s.partno\r\n"
		+ "            AND m.client=s.client\r\n"
		+ "            AND m.orgid=s.orgid\r\n"
		+ "            WHERE m.orgid=?1\r\n"
		+ "              AND m.branchcode=?2\r\n"
		+ "              AND m.client=?3\r\n"
		+ "              AND m.warehouse=?4\r\n"
		+ "            GROUP BY m.client, m.partno, m.partdesc, m.sku, m.criticalstocklevel\r\n"
		+ "            HAVING SUM(s.sqty) <= m.criticalstocklevel\r\n"
		+ "        ) t\r\n"
		+ "\r\n"
		+ "        UNION ALL\r\n"
		+ "        SELECT\r\n"
		+ "            'Over Stock Alert' AS type,\r\n"
		+ "            'Inventory Exceeds Maximum Level' AS description,\r\n"
		+ "            ?4 AS warehouse,\r\n"
		+ "            COUNT(*) AS totalcount\r\n"
		+ "        FROM\r\n"
		+ "        (\r\n"
		+ "            SELECT\r\n"
		+ "                m.client, m.partno, m.partdesc, m.sku,\r\n"
		+ "                m.maximumqty, SUM(s.sqty) AS qty\r\n"
		+ "            FROM material m\r\n"
		+ "            INNER JOIN stockdetails s\r\n"
		+ "            ON m.partno=s.partno\r\n"
		+ "            AND m.client=s.client\r\n"
		+ "            AND m.orgid=s.orgid\r\n"
		+ "            WHERE m.orgid=?1\r\n"
		+ "              AND m.branchcode=?2\r\n"
		+ "              AND m.client=?3\r\n"
		+ "              AND m.warehouse=?4\r\n"
		+ "            GROUP BY m.client, m.partno, m.partdesc, m.sku, m.maximumqty\r\n"
		+ "            HAVING SUM(s.sqty) > m.maximumqty\r\n"
		+ "        ) t\r\n"
		+ "    ) details_data\r\n"
		+ ") combined_data\r\n"
		+ "ORDER BY sno, type")
Set<Object[]> getEscalationDetails(Long orgId, String branchCode, String client, String warehouse);

}